name: multimedia
description: Multimedia libraries for pure dart with native bindings
version: 1.0.0
repository: https://github.com/ArcaneArts/multimedia
environment:
  sdk: ^3.5.2
dependencies:
  image_magick_ffi: ^0.0.1-dev.11
  thumbhash: ^0.1.0+1
  curse: ^1.0.3
  uuid: ^4.5.1
  toxic: ^1.3.1
dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
