name: multimedia
description: Multimedia libraries for pure dart with native bindings
version: 1.0.13
repository: https://github.com/ArcaneArts/multimedia
environment:
  sdk: ^3.5.2
dependencies:
  thumbhash: ">=0.1.0+1 <0.2.0"
  uuid: ">=3.0.0 <5.0.0"
  toxic: ">=1.3.1 <2.0.0"
  precision_stopwatch: ">=1.0.2 <2.0.0"
  ffi: ">=2.0.0 <3.0.0"
  image: ">=4.0.0 <5.0.0"
  ffmpeg_cli: ">=0.3.0 <0.4.0"
  mime: ">=2.0.0 <3.0.0"
dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
