name: multimedia
description: Multimedia libraries for pure dart with native bindings
version: 1.0.4
repository: https://github.com/ArcaneArts/multimedia
environment:
  sdk: ^3.5.2
dependencies:
  image_magick_ffi: ^0.0.1-dev.11
  thumbhash: ^0.1.0+1
  curse: ^1.0.3
  uuid: ">=3.0.0 <5.0.0"
  toxic: ^1.3.1
  precision_stopwatch: ^1.0.2
dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
